Distro: pop!_os
DE: gnome
# distro-version:
# de-version:
Install:
  Prescript:
    - openssh-config
  # ncdu htop
  Packages:
    - xfce4-terminal
    - xfce4-panel
    - xdotool
    - locate
    - gnome-tweaks
    - gnome-shell-extensions
    - chrome-gnome-shell
    - git
    - zsh
    - nemo
    - autojump
    - gir1.2-gtksource-4                # nemo-preview dependency
    - nemo-preview
    - sublime-text
    # - code
    # - ncdu
    # - htop
    # - tmux
    # - remmina
    # - xfreerdp
    # - font-manager
    - plank
    # - virtualbox
    # - virtualbox-ext-pack
  Snaps:
  Postscript:
    - mojave
    - kinto
    - homerc-files
    - git-projects
    # - touchpad-gnome-reverse
    - terminal-zsh-defaults
    # # - homebrew
    - autojump                  # Configures bash & zsh to source it
    - git-config
    - pop_os-defaults
    # - libinput-gestures
    # - hidpi-laptop-budgie
  # Done: echo "Congrats";
  #   echo "You are done!"
Remove:
  Packages: