Distro: Ubuntu
DE: Budgie
# distro-version:
# de-version:
Install:
  Prescript:
  Packages:
    - xfce4-terminal
    - git
    - zsh
    - autojump
    - nemo-preview
    - sublime-text
    - code
    - ncdu
    - htop
    - tmux
    - remmina
    - font-manager
    - budgie-hotcorners-applet
    - budgie-workspace-overview-applet
    - budgie-applications-menu-applet
    - budgie-appmenu-applet
    - budgie-indicator-applet
    - budgie-dropby-applet
    - budgie-network-manager-applet
    - xdotool                           # libinput-gestures
    - wmctrl                            # libinput-gestures
    - libinput-tools                    # libinput-gestures
    - python3                           # libinput-gestures
    # - gnome-software-plugin-flatpak
    # - virtualbox
    # - virtualbox-ext-pack
  Snaps:
  Postscript:
    - mojave
    - ubuntu-budgie-defaults
    - kinto
    - homerc-files
    - git-projects
    - touchpad-gnome-reverse
    - battery-gnome-percentage
    - time-12hr-gnome
    - terminal-zsh-defaults
    - autojump                  # Configures bash & zsh to source it
    - git-config
    - printer-fix
    - libinput-gestures
    # - flathub-repo
    # - homebrew
    # - hidpi-laptop-budgie
  # Done: echo "Congrats";
  #   echo "You are done!"
Remove:
  Packages: